### ISSUE TITLE
Command "bundle install" is failing

### ISSUE THREAD

**Issue by Raffaele** [bitrise-io/steps-script#14]
I have a script based on "bundle install" command, that particular command is failing and is breaking the process. The same command was succeeding until Friday, so I suppose something changed in the platform, can you please investigate?

Here an example of failing build today:
https://app.bitrise.io/build/850b6f87fbd77fc3#?tab=log
and here the same build succeed on Friday
https://app.bitrise.io/build/8cc450c5018e2791#?tab=log

**Comment by bitce** [comment]
Hi @Raffaele! 

I suspect there might have been an update of Ruby during this time, in case this problem is persistent at all for you, could you try running a script step before the step you're running the bundle install with the following contents?

```
#!/usr/bin/env bash
# fail if any commands fails
set -e
# debug log
set -x

rm ~/git/.ruby-version
```

**Comment by es0329** [comment]
My [build is failing](https://app.bitrise.io/build/7405fa7406149cc1#?tab=log) with this same issue but the suggestion from @bitce did not help.

**Comment by bitce** [comment]
Hi @es0329!

Sorry to hear about the issue. Can you please send us a build URL for the issue in the first place? The one you linked here was one where the recommended script failed due to not finding the file and it didn't expose the original issue.

**Comment by es0329** [comment]
Sure @bitce, [build #51](https://app.bitrise.io/build/1eef6f2ce4d91c7c#?tab=log) contained the initial failure.

**Comment by bitce** [comment]
Hmm, this doesn't seem to be the same issue 🤔 Can you let us know what are the contents of the script that's failing?

**Comment by es0329** [comment]
@bitce, This is the script that was working then began failing; which is what brought me [here](https://github.com/bitrise-steplib/steps-script/issues/14#issuecomment-577751963).
```
- script@1.1.5:
        inputs:
        - content: |-
            bundle install
            bundle exec danger
```

**Comment by bitce** [comment]
I think you'd have to start with a `gem install bundler` command here, can you give that a try?

**Comment by es0329** [comment]
Hmm @bitce, I don't recall needing `gem install bundler` previously when this was working, but I did give it a shot. It still [fails](https://app.bitrise.io/build/0c0ca2f5fa780231#?tab=log) though.

**Comment by istx25** [comment]
@es0329 Please let us know if you're no longer experiencing this issue.

With that said, can you clarify if you were doing `gem install bundler` or `gem install bundler:1.16.3`? If not, can you try the latter?

**Comment by es0329** [comment]
Hi @non-binary :) Your suggestion to specify a version with `gem install bundler:1.16.3` has restored my workflow's green status. Thank you for the insight!

**Comment by istx25** [comment]
Yay! Happy to hear that @es0329. Please don't hesitate to reach out if you need anything else.
