### ISSUE TITLE
Maven Appium testing

### ISSUE THREAD

**Issue by ivicar88** [bitrise-io/steps-script#15]
Hi,

I'm trying to add script which will start mave and tests I've add to app. These test are defined in POM file but bitrise is telling me that POM file can't be found in bitrise/src. Below is what is written in script. Am I missing something?

#!/usr/bin/env bash
set -e
# debug log
set -x
npm install -g appium
appium &>/dev/null &
mvn clean test

**Comment by bitce** [comment]
Hi @ivicar88!

Sorry for the long delay in our reply. Can you please include a build URL here so we can check out what's happening in the builds where you run this?
