### ISSUE TITLE
Script fails on Bash content that contains quotes

### ISSUE THREAD

**Issue by crrobinson14** [bitrise-io/steps-script#2]
The following script content will cause this step to fail with the error shown below:

```
#!/bin/bash
git log -n 5 --pretty=format:"%h - %s %cr <%an>" --abbrev-commit --date=relative
exit 0
```

Error is:

```
==> Start
/var/folders/4f/945ywsh506g31f58fpcbg0840000gn/T/bitrise519586167/step_src/step.sh: line 42: printf: ` ': invalid format character
/var/folders/4f/945ywsh506g31f58fpcbg0840000gn/T/bitrise519586167/step_src/._script_cont: line 3: unexpected EOF while looking for matching `"'
/var/folders/4f/945ywsh506g31f58fpcbg0840000gn/T/bitrise519586167/step_src/._script_cont: line 4: syntax error: unexpected end of file
```

This is because the script contains % characters to format Git logs. Is there a reason Bash printf is being used here? No format operators are included so it does not appear to serve a purpose. Why not use "echo" instead?

**Comment by viktorbenei** [comment]
We went with `printf` to save the content without an additional newline at it's end. Feel free to send a Pull Request with a fix, but if possible, we would like to keep this behaviour, to not to include additional newlines.

**Comment by crrobinson14** [comment]
Why not "echo -n"?

**Comment by viktorbenei** [comment]
Will that fix the issue? If yes, we're more than happy to use `echo -n` instead.

**Comment by crrobinson14** [comment]
Yes I believe it will (-n tells echo not to emit a newline). But how can I test and confirm? We're using this as it's brought through Steplib into Bitrise. I don't know how to prove it.

**Comment by viktorbenei** [comment]
You can fork this step and just run `bitrise run test` in it's directory - it contains a `bitrise.yml` configured for testing the step.

That said we already pushed a commit with this fix, and we'll release a new version as well soon.

**Comment by crrobinson14** [comment]
Excellent, thanks Viktor!

**Comment by viktorbenei** [comment]
`1.1.0` will be available in about a minute - if you use the `bitrise` CLI directly it's already available, on bitrise.io it'll be also available in less than a minute.

I'll close this issue, but feel free to comment if you experience a problem with the new version!

**Comment by crrobinson14** [comment]
Just FYI, confirmed working in 1.1.0.

**Comment by viktorbenei** [comment]
Thank you @crrobinson14 !
