### ISSUE TITLE
UI background color and syntax highlighting 

### ISSUE THREAD

**Issue by corganfuzz** [bitrise-io/steps-script#20]
As a new implementation for this step. could we have a black background for this step. similar to a terminal. also Bash syntax highlighting would be nice. It's really difficult to see for us who wear glasses in a 4k monitor

Right now, you have light gray background with grey letters if you are far sighted, then you'll be making a lot of mistakes

**Comment by bitce** [comment]
Hi @corganfuzz!

A 100% agreed. I will make sure to forward your request and have it gain attention.
