### ISSUE TITLE
xcode 12.5.1 not installed

### ISSUE THREAD

**Issue by bimawa** [bitrise-io/steps-script#23]
We need help ASAP. Please.

<img width="779" alt="CleanShot 2021-07-07 at 12 30 31@2x" src="https://user-images.githubusercontent.com/1393809/124718134-3a4c6f00-df1f-11eb-8610-f6e9dd21c99c.png">

Related [topic](https://discuss.bitrise.io/t/build-agent-still-has-xcode-12-5-installed/17286)

<img width="824" alt="CleanShot 2021-07-07 at 12 34 06@2x" src="https://user-images.githubusercontent.com/1393809/124718554-a4fdaa80-df1f-11eb-8d1f-1321a61a1426.png">

Looks like not yet.

**Comment by Roland-Bak** [comment]
Hello there @bimawa 👋

Sorry to hear about the issue, can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by bimawa** [comment]
@Roland-Bak I am so happy see you here 😄 
As I reply to support by e-email:
Ok I opened the access: https://app.bitrise.io/app/a43842eba8aec8ab#/settings
https://app.bitrise.io/app/a43842eba8aec8ab#
I’ll try describe the situation with issue. Our build has a lot of dependencies like binary frameworks and it builded with xcode 12.5.1 with swift 5.4.2.
if Bitrise will build our app with xcode 12.5.0 with swift 5.4 it will be not compatible and vice verse if we build our dependecies with xcode 12.5.0 we can’t build app with xcode 12.5.1
Sometimes Bitrise select xcode 12.5.0 sometime 12.5.1. looks like some VM using not updated stack.
We need some settings to force set up xcode version 12.5.1 not lower.

**Comment by bimawa** [comment]
@Roland-Bak I opened access again. Check it pls.

**Comment by bimawa** [comment]
@Roland-Bak Any news?  Should I build my app manually?

**Comment by Roland-Bak** [comment]
Hello @bimawa 👋

We are currently investigating this issue, but please note that this can take time. Once we know more, we'll let you know! 🙂

**Comment by bimawa** [comment]
> Hello @bimawa 👋
> 
> We are currently investigating this issue, but please note that this can take time. Once we know more, we'll let you know! 🙂

Sorry for abuse.  

Just investors found my home address.

**Comment by bimawa** [comment]
@Roland-Bak Support told to me, you fixed it!
<img width="407" alt="CleanShot 2021-07-09 at 09 43 09@2x" src="https://user-images.githubusercontent.com/1393809/125024439-3729be00-e09a-11eb-9087-009f4afb569d.png">

Thanks a lot!

**Comment by bimawa** [comment]
@Roland-Bak looks like fixed! Thanks a lot!
<img width="773" alt="CleanShot 2021-07-12 at 19 50 49@2x" src="https://user-images.githubusercontent.com/1393809/125308607-7c741700-e34a-11eb-8323-bbc3294215b3.png">
