### ISSUE TITLE
"npm bin" command does not support workspace

### ISSUE THREAD

**Issue by bishnushankar** [bitrise-io/steps-script#28]
### Issue description

I am running script on stack version 12.4, script execute command "npm bin" , but it is giving error. "command doesn't support workspace"

<img width="881" alt="Screenshot 2022-05-04 at 12 15 46 PM" src="https://user-images.githubusercontent.com/10974000/166652101-ca9b696d-d7fd-4912-a4bb-768524b36c0b.png">

**Comment by godrei** [comment]
Hi @bishnushankar ,

`npm bin` command is unaware of npm workspaces: https://docs.npmjs.com/cli/v7/commands/npm-bin#synopsis.
I assume your `package.json` file has `workspaces` property set, if so, it seems you can not use `npm bin` command.
