### ISSUE TITLE
Using custom nuget version script hangs while restoring packages

### ISSUE THREAD

**Issue by modplug** [bitrise-io/steps-script#3]
I'm using the custom nuget version script as described here:

http://devcenter.bitrise.io/docs/nuget-restore-with-custom-nuget-version

I set the nuget version to 3.3.0.
It always hangs on MvvmCross.DownloadCache, I did however try with another branch and another set of packages and I experienced the same issue (one of the packages would get stuck).
Downloading packages for this project takes about 24 seconds on my computer.

Restoring NuGet package Acr.UserDialogs.4.2.1.
Restoring NuGet package akavache.4.1.2.
Restoring NuGet package akavache.core.4.1.2.
Restoring NuGet package akavache.sqlite3.4.1.2.
Restoring NuGet package Cheesebaron.MvxPlugins.Sms.1.2.2.
Restoring NuGet package Microsoft.Bcl.1.1.10.
Restoring NuGet package Microsoft.Bcl.Async.1.0.168.
Restoring NuGet package Microsoft.Bcl.Build.1.0.21.
Restoring NuGet package Microsoft.Net.Http.2.2.29.
Restoring NuGet package modernhttpclient.2.4.2.
Restoring NuGet package MvvmCross.4.0.0.
Restoring NuGet package MvvmCross.Binding.4.0.0.
Restoring NuGet package MvvmCross.Core.4.0.0.
Restoring NuGet package MvvmCross.Platform.4.0.0.
Restoring NuGet package MvvmCross.Plugin.Color.4.0.0.
Restoring NuGet package MvvmCross.Plugin.DownloadCache.4.0.0.

**Comment by birmacher** [comment]
Hi @modplug!

The time difference between the build machines and your machine is because of the cached packages.
Can you please invite our support user to the app and we will take a look:
username: xamarin-support

**Comment by modplug** [comment]
Hi @birmacher.

Thanks for the fast reply! I've added xamarin-support to the app.
What kind of role should I set for the xamarin-support user?

**Comment by birmacher** [comment]
I run a test and it seems the NuGet hangs for some reason.
I'll close this ticket because it's unrelated to the repository and I'll follow up a bit later when I found out more about the issue.
