### ISSUE TITLE
Environment Variables are being replaced in this

### ISSUE THREAD

**Issue by ninjaprox** [bitrise-io/steps-script#7]
I tried with this simple case.

Script content

``` bash
echo $SECRET_KEY
```

Secret environment variable `SECRET_KEY=something`.

Then I got this in build log

```
echo something
something
```

As it states `Environment Variables won't be replaced in this input.`, I understand that the variable will not be replaced in the script content and what it supposes to be

```
echo $SECRET_KEY
something
```

Wondering if I'm misunderstanding or it's a bug.

**Comment by viktorbenei** [comment]
You used the `set -x` Bash flag most likely in your Script, which prints the command in its final / expanded form. `set -v` prints it in unexpanded form.

**Comment by viktorbenei** [comment]
If you don't use any of these the the echo line should not be in your log, Bash does not print the command (only the command's output) unless you set one of these flags.

**Comment by ninjaprox** [comment]
You're correct. Thanks!
