### ISSUE TITLE
Pipe not supported

### ISSUE THREAD

**Issue by leesah** [bitrise-io/steps-script#8]
I created a Script step:

    - script@1.1.3:
        title: Kill Running Emulator
        is_always_run: true
        inputs:
        - content: |-
            #!/bin/bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            adb devices | grep device | cut -f1 | xargs -I_ adb -s _ emu kill

, which when run turned into:
 
    +------------------------------------------------------------------------------+
    | (0) Kill Running Emulator                                                    |
    +------------------------------------------------------------------------------+
    | id: script                                                                   |
    | version: 1.1.3                                                               |
    | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
    | toolkit: bash                                                                |
    | time: 2017-04-23T20:29:25Z                                                   |
    +------------------------------------------------------------------------------+
    |                                                                              |
    + adb devices
    + grep device
    + cut -f1
    + xargs -I_ adb -s _ emu kill
    |                                                                              |
    +---+---------------------------------------------------------------+----------+
    | x | Kill Running Emulator (exit code: 123)                        | 0.47 sec |
    +---+---------------------------------------------------------------+----------+
    | Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
    | Source: https://github.com/bitrise-io/steps-script                           |
    +---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Hi,

This is not a script/step issue, this is how `set -x` prints the commands. `set -x` prints every command before it would execute it.

In your case it means:

1. Ran `adb devices` - was OK
1. Ran `grep devices` - was OK
1. Ran `cur -f1` - was OK
1. Ran `xargs ..` -> failed

(Technically "was OK" doesn't mean that the command was successful, just that it did run it, the exit code of the piped command is the exit code of the last command, by default).

You can try this by simply saving the script into a file and then run it with `bash ./path/to/script.sh` (note: this step basically does this, it saves the script into a file and then runs it), or simply run `set -x` in your Terminal (if you use bash as your shell) to enable Bash's "debug logging".

If you have any questions just let us know!
